AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  UploadBucketName:
    Type: String
    Description: "The name of the S3 bucket to upload to"
  StageName:
    Type: String
    Default: Dev
    Description: "The name of the API Gateway stage (e.g., Dev, Prod)"

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: ApiGateway
      StageName: !Ref StageName
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  CoreApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: fastapi_app.__init__.handler
      Runtime: python3.12
      CodeUri: .
      MemorySize: 128
      Timeout: 5
      Environment:
        Variables:
          UPLOAD_BUCKET: !Ref UploadBucketName
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGateway
